version: '3'

# All of these servers should have their ports exposed, but because we're using --scale we're not going to.
services:
  fd-introducer:
    container_name: fd-introducer
    environment:
      - INTRODUCER=1
    ports:
      - "6002:6002"
      - "6004:6004"
    build: .

  worker:
    build: .
