version: '3'

# All of these servers should have their ports exposed, but because we're using --scale we're not going to.
services:
  introducer:
    container_name: introducer
    environment:
      - INTRODUCER=1
    ports:
      - "6002:6002"
      - "6004:6004"
    build: .

  worker:
    # Delay building this container until introducer is ready
    depends_on:
      - "introducer"
    build: .
